### ISSUE TITLE
how can I wrap return type `std::vector<cv::Vec3b>`

### ISSUE THREAD

**Issue by wenmin-wu** [renatoGarcia/opencv-swig#10]
Hi renato,
Thanks for you remarkable work! I wrote a cpp code the return type of the function is `std::vector<cv::Vec3b>` and  I want to wrap it to `list<Vec3b>` in python. How to write the `*i`.
Thanks!

**Comment by renatoGarcia** [comment]
Hi wenmin-wu,
You will need tell to swig instantiate the template class `std::vector<cv::Vec3b>`.
A code like this will work.

my_lib.hpp:
```C++
#include <opencv2/core.hpp>
#include <vector>

inline
std::vector<cv::Vec3b> bla()
{
    std::vector<cv::Vec3b> aaa;
    aaa.push_back(cv::Vec3b(1, 2, 3));
    aaa.push_back(cv::Vec3b(10, 11, 12));
    return aaa;
}
```

my_lib.i:
```
%module my_lib

%include <opencv.i>
%include <std_vector.i>

%cv_instantiate_all_defaults
%template(vectorVec3b) std::vector<cv::Vec3b>;

%{
    #include "my_lib.hpp"
%}

%include "my_lib.hpp"
```

**Comment by keyxuliang** [comment]
Hi ,
if a fuction in  my_lib.hpp, such as:
inline
std::vector\<cv::Vec3b\> bla(cv::Mat mat)
How to use it in Python? Or how define the 'm'
    m= xxx
    my_lib.bla(m)
I only can use: "m= my_lib.Mat()",but can't pass data to the function 'bla' by this way.

**Comment by renatoGarcia** [comment]
The call of `bla` with one argument is just like the call of `moveTo` on the [hello world example](https://github.com/renatoGarcia/opencv-swig#hello-world). Have you gone through all the hello world example with no problems?

**Comment by keyxuliang** [comment]
The example works! 
As mentioned above, I mean that how to initialize the variable  "m" or assign values to "m", which is "my_lib.Mat".
For example:
m= my_lib.Mat(2,3,1)#matrix "m"contains 2 rows 3cols
m[0,0]=1 # incorrect
my_lib.bla(m)

Or 
m=np.array([[1,2,3],[4,5,6]])
my_lib.bla(m) # argument type is incorrect
So, how to define the variable "m", which is a matrix, such as [[1,2,3],[4,5,6]]

**Comment by renatoGarcia** [comment]
Currently there is no support to set OpenCV Mat elements (PR's welcome :-) ). A workaround is work with NumPy arrays and create a OpenCV MatX using the `from_array` class method. No data will be copied, so the operation is fast, and any modification on the OpenCV Mat will be done on NumPy array too.

To convert from a NumPy array to a OpenCV Mat:

    np_array = np.array([[1,2,3],[4,5,6]], dtype=np.uint8)
    cv_mat = my_lib.Mat1b.from_array(np_array)

To convert from a OpenCV Mat to a NumPy array:

    np_array2 = np.asarray(cv_mat)
