### ISSUE TITLE
Function arguments about "vector<Point2f> points"

### ISSUE THREAD

**Issue by keyxuliang** [renatoGarcia/opencv-swig#13]
Hi ,
I define a function , it has the arguments:  "vector\<Point2f\> points" and  "Mat& trans_mat"  and “float& fnum” in c++.
Now  I want to know how to wrap and use the function in Python.
Thanks!

**Comment by renatoGarcia** [comment]
Hi keyxuliang,

The `Mat& trans_mat` and `float& fnum` will be handled by opencv-swig by default, just as in the [hello world](https://github.com/renatoGarcia/opencv-swig#hello-world) example.
To the `vector<Point2f> points` argument you must tell to swig to wrapper that std::vector template instantiation, just follow the instructions at [this other answer](https://github.com/renatoGarcia/opencv-swig/issues/10#issuecomment-397472969).

**Comment by keyxuliang** [comment]
Hi renatoGarcia,
I find a new problem:
I define a funcition in cpp, it's return type  "vector<Point2f>", and wrap it:
        ......
	vector<Point2f> centerPoints;
	......
	return centerPoints;
But it can't works in python when call the funtion:
"<Swig Object of type 'vector< Point2f > *' at 0x000001FE868DCF30>
swig/python detected a memory leak of type 'vector< Point2f > *', no destructor found."

How to solve this problem?
Thanks!

**Comment by renatoGarcia** [comment]
Could you share a [minimal working example](https://stackoverflow.com/help/mcve) where you are having that problem?

**Comment by keyxuliang** [comment]
I modified "vectot<Point2f>" to "std::vectot<cv::Point2f>" at return type of function. Then It works, although I used "using namespace std; using namespace cv;". But I don't know the reasons.
