### ISSUE TITLE
 Unable to find 'opencv.i')

### ISSUE THREAD

**Issue by leemengwei** [renatoGarcia/opencv-swig#14]
Hello,   what is the <path to OpenCV-SWIG library>?  how to install them? 
I tried `sudo apt-get install swig` and still couldn't find it. (my_lib.i:3: Error: Unable to find 'opencv.i')

**Comment by renatoGarcia** [comment]
Hello leemengwei.
It seems like the SWIG is correctly installed on your system. The opencv.i file is not part of SWIG, it is part of this 'opencv-swig' library. At the command:
`swig -I<path to OpenCV-SWIG library> -python -c++ my_lib.i`
You must change the `<path to OpenCV-SWIG library>` by the path to where you have put this library.
What was the command exactly that you have used?
