### ISSUE TITLE
How to convert numpy array(python) to a cv::Mat(c++)?

### ISSUE THREAD

**Issue by tabsun** [renatoGarcia/opencv-swig#15]
As cv2 takes all image as numpy array, how can I make the c/c++ code to receive np.array?
Does this lib support it?

**Comment by renatoGarcia** [comment]
If I have correctly understood your use case, your main program is written in Python, it's using the OpenCV library through the Python bindings, and you wish write a C++ lib to be called by the main Python program, and that C++ lib will receive the cv2 images represented as numpy arrays.

If that is the case, you have two options. The first one is use this lib, write the C++ code receiving and returning the the OpenCV classes as usual. On Python land, to convert from NumPy arrays to OpenCV classes use the `from_array` methods like:
https://github.com/renatoGarcia/opencv-swig/blob/8113bc35ee6e9d61efae3ad3c1087b11acd6ac03/test/test_mat.py#L37
To convert from OpenCV classes to NumPy arrays use the `np.asarray` as:https://github.com/renatoGarcia/opencv-swig/blob/8113bc35ee6e9d61efae3ad3c1087b11acd6ac03/test/test_mat.py#L56

A second option is to use the NumPy SWIG interface file. Look at the NumPy [documentation](https://docs.scipy.org/doc/numpy/reference/swig.interface-file.html).

**Comment by tabsun** [comment]
Much thanks for your help and it really solved my problem. Great work!
