### ISSUE TITLE
std::vector<cv::Mat>

### ISSUE THREAD

**Issue by huckw** [renatoGarcia/opencv-swig#18]
Hello,

Thanks for the great code.  I do have another question.  I have wrapped a function that takes a `cv::Mat` and I can call it from python simply by

```
I=cv2.imread('/path/to/image1.png')
my_lib.myfunction(my_lib.Mat.from_array(I))
```

Now I have a different signature that takes  a `std::vector<cv::Mat>` and  I added this little bit at bottom of my interface file...

```
%include "std_vector.i"
namespace std {
    %template(vectormat) vector<cv::Mat>;
}
```
So then I do this...
```
imgs=[]
I=cv2.imread('/path/to/image1.png')
imgs.append(my_lib.Mat.from_array(I))
I=cv2.imread('/path/to/image2.png')
imgs.append(my_lib.Mat.from_array(I))
my_lib.myfunction(imgs) # this does NOT work
workaround=my_lib.vectormat(imgs)
my_lib.myfunction(workaround) # this works, but feels clunky
```
Is there a solution that avoids the clunky "workaround"?

**Comment by renatoGarcia** [comment]
There is a solution, but not a simple one. The problem lies on C++ overload resolution. Say you have two functions:
```C++
void myfunction(std::vector<cv::Mat>& ar);
void myfunction(std::list<cv::Mat>& ar);
```

When you do:
```Python
imgs=[]
I=cv2.imread('/path/to/image1.png')
imgs.append(my_lib.Mat.from_array(I))
I=cv2.imread('/path/to/image2.png')
imgs.append(my_lib.Mat.from_array(I))
my_lib.myfunction(imgs)
```
Which one of those two function should be called? If you change the `ar` argument inside the function, should the Python `imgs` list be changed too?

The default SWIG approach is force you to use an explicit wrapper to a `std::vector` or `std::list`. However, if you really wish to use a Python list directly, your way to that is through SWIG [Typemaps](http://swig.org/Doc4.0/SWIGDocumentation.html#Typemaps).

**Comment by huckw** [comment]
I think I get it....thank you!

**Comment by huckw** [comment]
Here is a weird thing (not sure if it is related).  But I have some std::vector<float> that I have to deal with and so I added what I though was the correct %template...
```
%include "std_vector.i"
namespace std {
    %template(vectormat) vector<cv::Mat>;
    %template(vectorfloat) vector<float>;
}
```
However, I get a compile error...

Error	C2084	function 'swig::SwigPyIterator *std_vector_Sl_float_Sg__iterator(std::vector<float,std::allocator<float>> *,PyObject **)' already has a body	

Does this mean that std::vector<> of standard types are already taken care of?  If so, how do I use them?  

I am sorry if this is unrelated to my previous question and/or unrelated to your nice project.

**Comment by renatoGarcia** [comment]
Yes, it is a bug on this lib. At [this](https://github.com/renatoGarcia/opencv-swig/blob/1c380ed71dda8f50ca212ffda23555ca453b28f2/lib/opencv/matx.i#L47) line, the `std::vector` is being instantiated to the same type as the `cv::Matx`. By default `float` and `double`. That is required by [this](https://github.com/renatoGarcia/opencv-swig/blob/1c380ed71dda8f50ca212ffda23555ca453b28f2/lib/opencv/matx.i#L167) function.

It should be possible rework that function to not use a `std::vector` anymore. Meanwhile, a workaround is use the instances from inside opencv-swig, `my_lib._floatArray` and `my_lib._doubleArray`.

**Comment by Aquapisces** [comment]
> Yes, it is a bug on this lib. At [this](https://github.com/renatoGarcia/opencv-swig/blob/1c380ed71dda8f50ca212ffda23555ca453b28f2/lib/opencv/matx.i#L47) line, the `std::vector` is being instantiated to the same type as the `cv::Matx`. By default `float` and `double`. That is required by [this](https://github.com/renatoGarcia/opencv-swig/blob/1c380ed71dda8f50ca212ffda23555ca453b28f2/lib/opencv/matx.i#L167) function.
> 
> It should be possible rework that function to not use a `std::vector` anymore. Meanwhile, a workaround is use the instances from inside opencv-swig, `my_lib._floatArray` and `my_lib._doubleArray`.

I work out the way to this bug:
open ....\opencv-swig-master\lib\opencv\matx.i, look for:
` #if !_ARRAY_##type##_INSTANTIATED_
        %template(_##type##Array) std::vector< type >;
        %pythoncode
        {
            _array_map[#type] = _##type##Array
        }
        #define _ARRAY_##type##_INSTANTIATED_
    #endif`
delete the underscor of `_##type##Array` , then it works correctly

**Comment by renatoGarcia** [comment]
Hi @Aquapisces. Could you post a working example compiling the [this code](https://github.com/renatoGarcia/opencv-swig/issues/18#issuecomment-531840055)?
