### ISSUE TITLE
Is Boost required?

### ISSUE THREAD

**Issue by huckw** [renatoGarcia/opencv-swig#2]
I get `fatal error C1083: Cannot open include file: 'boost/preprocessor/repetition/repeat_from_to.hpp': No such file or directory`.  I do not have boost (and am trying to avoid using it if possible).  Is it required for opencv-swig?

**Comment by renatoGarcia** [comment]
Yes, sorry, it is required. The Boost Preprocessor library saves a lot of boilerplate and error prone code where it is being used.

However, all included boost code is header only. You won't need neither to link nor distribute any boost library along your program. Furthermore, as opencv-swig uses only the Boost Preprocessor, you won't even need to compile the boost libraries. Just downloading and unpacking the boost source in some directory will work.
