### ISSUE TITLE
C++ struct contain cv::Mat

### ISSUE THREAD

**Issue by samguodq** [renatoGarcia/opencv-swig#21]
Hello,
Thank you for  code. It's very helpful to me. I have a question about how to wrap struct contain cv::Mat.
struct MyStruct {
    cv::Mat image;
};

Thank you very much for your help!

**Comment by renatoGarcia** [comment]
Hi @samguodq, sorry for the late response. I don't get what are your doubt. Just copying this struct code to the [C++ code at example](https://github.com/renatoGarcia/opencv-swig#hello-world) and following the same instructions will create you a Python wrap to `MyStruct`. With this you will be able to construct and access the image attribute, and pass/receive it to functions.
