### ISSUE TITLE
Does this opencv-Swig only work with python?

### ISSUE THREAD

**Issue by 0vz-llu** [renatoGarcia/opencv-swig#33]
Hello, i would like to ask if this opencv-Swig is only applicable to python, but not to CSharp code.i successfully ran Python, but when I tried to use CSharp, there would be an error, because there is %pythoncode in numpy. I file.
![123](https://github.com/user-attachments/assets/c72b702a-a041-481e-8a37-4f92cd3c7879)

**Comment by renatoGarcia** [comment]
Hi @0vz-llu,

Yes, this project was designed targeting just Python. Because of that it even has those Python directives.
Sadly it won't support other languages without a substantial effort.

**Comment by 0vz-llu** [comment]
> Hi @0vz-llu,
> 
> Yes, this project was designed targeting just Python. Because of that it even has those Python directives. Sadly it won't support other languages without a substantial effort.

Thank you sincerely for your reply. A good person lives a peaceful life.
