### ISSUE TITLE
get some error: Unable to find 'opencv2\core\version.hpp'

### ISSUE THREAD

**Issue by LzxHahaha** [renatoGarcia/opencv-swig#4]
I try to use like this:
```
$ swig -ID:\swigwin\opencv-swig\lib -python -c++ Saliency.i
```

then I got those message:
```
D:\swigwin\opencv-swig\lib\opencv\detail\range.i(12) : Error: Unable to find 'opencv2\core\version.hpp'
D:\swigwin\opencv-swig\lib\opencv\detail\matx.i(12) : Error: Unable to find 'opencv2\core\version.hpp'
D:\swigwin\opencv-swig\lib\opencv\detail\vec.i(12) : Error: Unable to find 'opencv2\core\version.hpp'
D:\swigwin\opencv-swig\lib\opencv\detail\point.i(12) : Error: Unable to find 'opencv2\core\version.hpp'
D:\swigwin\opencv-swig\lib\opencv\detail\size.i(12) : Error: Unable to find 'opencv2\core\version.hpp'
D:\swigwin\opencv-swig\lib\opencv\detail\rect.i(12) : Error: Unable to find 'opencv2\core\version.hpp'
D:\swigwin\opencv-swig\lib\opencv\detail\scalar.i(12) : Error: Unable to find 'opencv2\core\version.hpp'
D:\swigwin\opencv-swig\lib\opencv\detail\mat.i(12) : Error: Unable to find 'opencv2\core\version.hpp'
```

I tried to add `opencv\build\include` into environment variables, but still can not work. How to fixed it?

I'm using Windows 10, python 2.7.13 and OpenCV 2.4.13

**Comment by LzxHahaha** [comment]
Add `-I<OpenCV path>` then it successed.

**Comment by Ramesh-X** [comment]
It is not `OpenCV path`. You have to add `-I%OPENCV_DIR%\..\..\include` to the swig command.

%OPENCV_DIR% is the path to opencv build directory as described in opencv documentation.  (eg: `D:\OpenCV\build2\install\x64\vc12`)

**Comment by Aquapisces** [comment]
> It is not `OpenCV path`. You have to add `-I%OPENCV_DIR%\..\..\include` to the swig command.
> 
> %OPENCV_DIR% is the path to opencv build directory as described in opencv documentation. (eg: `D:\OpenCV\build2\install\x64\vc12`)

I tried
` swig -I D:\C++\3rdParty\opencv\build\x64\vc15`
but it shows
` Unable to find file 'D:\C++\3rdParty\opencv\build\x64\vc15'.`
I'm using OpenCV4. What file directory should be referred here, please?

**Comment by Aquapisces** [comment]
> Add `-I<OpenCV path>` then it successed.

would you please show the entire swig command?
