### ISSUE TITLE
failed to build

### ISSUE THREAD

**Issue by yayo13** [renatoGarcia/opencv-swig#9]
i followed your step, and use setup.py to build
`from distutils.core import setup, Extension

pht_module = Extension('_my_lib', 
                        sources=['my_lib_wrap.cxx', 
                                ],
                      )

setup(name = 'my_lib',
        version = '0.1',
        author = '',
        description = '',
        ext_modules = [pht_module], 
        py_modules = ['my_lib'],
    )`

but get many errors:
`my_lib_wrap.cxx:6405:40: error: template argument 1 is invalid
         return new cv::Mat_<(cv::Vec2i)>(rows, cols, (cv::Mat_<(cv::Vec2i)>::value_type*)data);
my_lib_wrap.cxx:6413:75: error: template argument 1 is invalid
         return new cv::Mat_<(cv::Vec3i)>(rows, cols, (cv::Mat_<(cv::Vec3i)>::value_type*)data);
...
`
i'm use ubuntu14.04, python2.7.6, opencv2.4.13.6

**Comment by renatoGarcia** [comment]
Hi yayo13,
Sorry for the (very) late response.
Could you share a minimal project reproducing this problem?
Do you have that same error when compiling the code from CLI, without the Python distutils?
